### ISSUE TITLE
BM1366_INITIAL_DIFFICULTY @ 2048 is too high.

### ISSUE THREAD

**Issue by skot** [bitaxeorg/esp-miner-multichip#9]
setting the chip difficulty mask at 2048 does not allow the hex to generate shares fast enough for some pools. 

For example Kano pool wants shares @ 18 per minute. According to STS Miner the sweet spot is 9 - 16 shares per minute.

Of course you want the chip difficulty to be lower than the pool difficulty, so that a reasonable hashrate can be calculated on the miner.

The single chip Bitaxe is set to 256, so this should probably be 1536, or less.

**Comment by tqvalenca** [comment]
@skot yo your site (skot9000.com) is down
